<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EquityPositions.Core\EquityPositions.Core.csproj" />
    <ProjectReference Include="..\EquityPositions.DataAccess\EquityPositions.DataAccess.csproj" />
  </ItemGroup>

</Project>
